### ISSUE TITLE
Add support for Facebook nicknames

### ISSUE THREAD

**Issue by Bjornskjald** [Bjornskjald/messenger-discord#15]

**Comment by ShinNinth** [comment]
@Bjornskjald This isnt quite the facebook nicknames help you wanted but i have made an adjustment to the discord listener to include discord username with the message being sent.  The edit is in the msg var ive included the snippet below

`  var msg = message.attachments.size > 0 ? {body: message.author.username + ': ' + message.content, url: message.attachments.first().url} : {body: message.author.username + ': ' + message.content}  `

I'll keep digging through the API docs and see if i cant get a handle on the nicknames next

**Comment by Bjornskjald** [comment]
Will you be able to create a pull request with this?

**Comment by Bjornskjald** [comment]
Moved your issue to #20
