### ISSUE TITLE
Receiving Group message creates duplicate channels

### ISSUE THREAD

**Issue by ShinNinth** [Bjornskjald/messenger-discord#18]
Currently when you receive a message on a group channel in FB the bridge application is making duplicate channels on discord every time the FB group chat receives a new message. 

BTW @Bjornskjald I am having a blast QA testing your app and would love to help you out more but i know absolutely nothing of the two api's your using if you wanted to msg me some places to start reading i will get working on catching up to help you out with this.

**Comment by Bjornskjald** [comment]
@ShinNinth Thanks for the info, it has to be a mistake in detecting if channel is already created...
Here are the two APIs I'm using:
Discord: https://discord.js.org/#/docs/main/stable/general/welcome
Messenger: https://github.com/Schmavery/facebook-chat-api/
It would be nice if you'd like to help me, thanks!

**Comment by ShinNinth** [comment]
@Bjornskjald I received an error while i left it running and was at work.  Some context to this i had removed all of the duplicate channels so the bot had no channels left before i left for work thinking it would just create a new one again.

`WARN parseAndCheckLogin Got status code 502 - 1. attempt to retry in 106 milliseconds...
ERR! listen Error: parseAndCheckLogin got status code: 400. Bailing out of trying to parse response.
ERR! listen     at C:\messenger-discord-master\node_modules\facebook-chat-api\utils.js:843:42
ERR! listen     at tryCatcher (C:\messenger-discord-master\node_modules\bluebird\js\main\util.js:26:23)
ERR! listen     at Function.Promise.attempt.Promise.try (C:\messenger-discord-master\node_modules\bluebird\js\main\method.js:31:24)
ERR! listen     at C:\messenger-discord-master\node_modules\facebook-chat-api\utils.js:813:24
ERR! listen     at tryCatcher (C:\messenger-discord-master\node_modules\bluebird\js\main\util.js:26:23)
ERR! listen     at Promise._settlePromiseFromHandler (C:\messenger-discord-master\node_modules\bluebird\js\main\promise.js:510:31)
ERR! listen     at Promise._settlePromiseAt (C:\messenger-discord-master\node_modules\bluebird\js\main\promise.js:584:18)
ERR! listen     at Async._drainQueue (C:\messenger-discord-master\node_modules\bluebird\js\main\async.js:128:12)
ERR! listen     at Async._drainQueues (C:\messenger-discord-master\node_modules\bluebird\js\main\async.js:133:10)
ERR! listen     at Immediate.Async.drainQueues (C:\messenger-discord-master\node_modules\bluebird\js\main\async.js:15:14)
ERR! listen     at runCallback (timers.js:789:20)
ERR! listen     at tryOnImmediate (timers.js:751:5)
ERR! listen     at processImmediate [as _immediateCallback] (timers.js:722:5)
ERR! listen  Error: parseAndCheckLogin got status code: 400. Bailing out of trying to parse response.
ERR! listen     at C:\messenger-discord-master\node_modules\facebook-chat-api\utils.js:843:42
ERR! listen     at tryCatcher (C:\messenger-discord-master\node_modules\bluebird\js\main\util.js:26:23)
ERR! listen     at Function.Promise.attempt.Promise.try (C:\messenger-discord-master\node_modules\bluebird\js\main\method.js:31:24)
ERR! listen     at C:\messenger-discord-master\node_modules\facebook-chat-api\utils.js:813:24
ERR! listen     at tryCatcher (C:\messenger-discord-master\node_modules\bluebird\js\main\util.js:26:23)
ERR! listen     at Promise._settlePromiseFromHandler (C:\messenger-discord-master\node_modules\bluebird\js\main\promise.js:510:31)
ERR! listen     at Promise._settlePromiseAt (C:\messenger-discord-master\node_modules\bluebird\js\main\promise.js:584:18)
ERR! listen     at Async._drainQueue (C:\messenger-discord-master\node_modules\bluebird\js\main\async.js:128:12)
ERR! listen     at Async._drainQueues (C:\messenger-discord-master\node_modules\bluebird\js\main\async.js:133:10)
ERR! listen     at Immediate.Async.drainQueues (C:\messenger-discord-master\node_modules\bluebird\js\main\async.js:15:14)
ERR! listen     at runCallback (timers.js:789:20)
ERR! listen     at tryOnImmediate (timers.js:751:5)
ERR! listen     at processImmediate [as _immediateCallback] (timers.js:722:5)
Error: parseAndCheckLogin got status code: 400. Bailing out of trying to parse response.
    at C:\messenger-discord-master\node_modules\facebook-chat-api\utils.js:843:42
    at tryCatcher (C:\messenger-discord-master\node_modules\bluebird\js\main\util.js:26:23)
    at Function.Promise.attempt.Promise.try (C:\messenger-discord-master\node_modules\bluebird\js\main\method.js:31:24)
    at C:\messenger-discord-master\node_modules\facebook-chat-api\utils.js:813:24
    at tryCatcher (C:\messenger-discord-master\node_modules\bluebird\js\main\util.js:26:23)
    at Promise._settlePromiseFromHandler (C:\messenger-discord-master\node_modules\bluebird\js\main\promise.js:510:31)
    at Promise._settlePromiseAt (C:\messenger-discord-master\node_modules\bluebird\js\main\promise.js:584:18)
    at Async._drainQueue (C:\messenger-discord-master\node_modules\bluebird\js\main\async.js:128:12)
    at Async._drainQueues (C:\messenger-discord-master\node_modules\bluebird\js\main\async.js:133:10)
    at Immediate.Async.drainQueues (C:\messenger-discord-master\node_modules\bluebird\js\main\async.js:15:14)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)`

**Comment by Bjornskjald** [comment]
Kind of unexpected, because it isn't a problem in my code, but in facebook-chat-api, unless some APIs changed again...

**Comment by Bjornskjald** [comment]
Can you try replacing facebook-chat-api with npm version by running in the console `npm install facebook-chat-api`?

**Comment by ShinNinth** [comment]
I may have caused this to happen by deleting all those duplicate channels and not leaving one.  I left this running overnight and did not see the error come up again.  I will reload the API

**Comment by ShinNinth** [comment]
The other thing i have noticed with the dupe channels is the channel topics are all different numbers.  Is the bot determining the channels by their topics?

**Comment by ShinNinth** [comment]
So i think ive got the duplicate issue figured out.  it seems the first channel find section of the getchannel.js is failing because of the && channel.parent === parent  requirement.  I commented this out and reran the bot and it looks like it is not duplicating the channel now.   I also commented that out on the topic section as well before doing the channel itself with no results so im not sure what was causing the topic check to fail.

**Comment by Bjornskjald** [comment]
So it may be caused by category not matching up or something... I don't have much time this week, but I'll try to find some and fix this

**Comment by Bjornskjald** [comment]
Apparently, it still does

**Comment by Bjornskjald** [comment]
Needs more testing...

**Comment by foogoos** [comment]
could you have an option to just specify facebook messenger chat names and match them with discord channel IDs? i updated the facebook api thing too and still get a lot of errors and duplicate channels

**Comment by Bjornskjald** [comment]
@foogoos Discord channel IDs are read-only so it's impossible to change them to messenger thread IDs, if that's what you meant.
If you meant discord channel names, it would be hard to track channels if duplicate names of groups occur.
I'm coming back today so I'll try to test this and fix any bugs
also, could you paste errors you get here so I can check where are they occuring?

**Comment by Bjornskjald** [comment]
Apparently, subchannels of specific category doesn't update automatically...
