### ISSUE TITLE
parseAndCheckLogin got status code: 404 Bailing out of trying to parse response.

### ISSUE THREAD

**Issue by ShinNinth** [Bjornskjald/messenger-discord#19]
After the adjustments i made to eliminate duped channels everything was working fine but it looks like it crashed out after some time with this error

`ERR! getUserInfo  Error: parseAndCheckLogin got status code: 404. Bailing out of trying to parse response.
ERR! getUserInfo     at C:\messenger-discord-master\node_modules\facebook-chat-api\utils.js:843:42
ERR! getUserInfo     at tryCatcher (C:\messenger-discord-master\node_modules\bluebird\js\main\util.js:26:23)
ERR! getUserInfo     at Function.Promise.attempt.Promise.try (C:\messenger-discord-master\node_modules\bluebird\js\main\method.js:31:24)
ERR! getUserInfo     at C:\messenger-discord-master\node_modules\facebook-chat-api\utils.js:813:24
ERR! getUserInfo     at tryCatcher (C:\messenger-discord-master\node_modules\bluebird\js\main\util.js:26:23)
ERR! getUserInfo     at Promise._settlePromiseFromHandler (C:\messenger-discord-master\node_modules\bluebird\js\main\promise.js:510:31)
ERR! getUserInfo     at Promise._settlePromiseAt (C:\messenger-discord-master\node_modules\bluebird\js\main\promise.js:584:18)
ERR! getUserInfo     at Promise._settlePromises (C:\messenger-discord-master\node_modules\bluebird\js\main\promise.js:700:14)
ERR! getUserInfo     at Async._drainQueue (C:\messenger-discord-master\node_modules\bluebird\js\main\async.js:123:16)
ERR! getUserInfo     at Async._drainQueues (C:\messenger-discord-master\node_modules\bluebird\js\main\async.js:133:10)
ERR! getUserInfo     at Immediate.Async.drainQueues (C:\messenger-discord-master\node_modules\bluebird\js\main\async.js:15:14)
ERR! getUserInfo     at runCallback (timers.js:789:20)
ERR! getUserInfo     at tryOnImmediate (timers.js:751:5)
ERR! getUserInfo     at processImmediate [as _immediateCallback] (timers.js:722:5)`

Not sure why chat wasnt very active

**Comment by Bjornskjald** [comment]
this error seems like it's not related to duplicate channels...

**Comment by Bjornskjald** [comment]
Opened an issue in Schmavery/facebook-chat-api, because error occurs in this module, not mine code
