### ISSUE TITLE
Empty messages are being sent

### ISSUE THREAD

**Issue by Bjornskjald** [Bjornskjald/messenger-discord#29]

**Comment by wdbrs** [comment]
I'm actually still having this problem.  I just installed it via GitHub Desktop, it appears to be the latest version. I cloned the "Bjornskjald/miscord" repository to get it set up.  I'm unsure if I'm missing anything, this is only my second time using GitHub

**Comment by Bjornskjald** [comment]
Duplicate messages should disappear quickly, if they don't and they annoy you, there is a switch in the config

**Comment by wdbrs** [comment]
I'm not getting duplicates, I'm getting single messages with no text at all.  Messages from Discord go through right, but ones from Facebook come through empty/blank.  Is this a different issue?

**Comment by Bjornskjald** [comment]
That's... weird. Moved this to #79
