### ISSUE TITLE
Make documentation more clear

### ISSUE THREAD

**Issue by raniesantos** [Bjornskjald/messenger-discord#4]

**Comment by Bjornskjald** [comment]
@raniesantos sorry, I wasn't checking issues for this project.
i'm gonna try to make readme more detailed, can you tell me where have you failed in installing/setup?

**Comment by ShinNinth** [comment]
@Bjornskjald I recently came across this as well I am attemtping to run this on a windows OS  and I am getting a syntax error when trying to run login.js is this unable to be run on windows?  The instructions for use on linux distros is decent but there isnt much info other then setting the vars for a windows setup

**Comment by Bjornskjald** [comment]
@ShinNinth afaik it should work on Windows as well as on Linux, but I'm gonna test it today and eventually fix any bugs.

**Comment by Bjornskjald** [comment]
@ShinNinth what version of Node.js do you have?

**Comment by ShinNinth** [comment]
I did not have node js i was attempting to run through wscript which was probly why i was getting a syntax error.  After switching to node and getting my git setup in the PATH environment var to get the api downloaded as well i am no longer getting the syntax error.  I am not sure savvy other users are but setting all of that up for windows is a lot to look up you may want to think about linking to some guides for it or directly implementing it into your setup docs.  Thanks for the help with what i was doing wrong.

**Comment by ShinNinth** [comment]
Also now that i have it running any time i send it a message i get a parseAndCheckLogin got status code: 404 error.   Also will this trigger on group chats?

**Comment by Bjornskjald** [comment]
@ShinNinth The "parseAndCheckLogin" error is probably from "facebook-chat-api" module by Schmavery, but will you be able to give me more details? Logs after error showing up would be great.
I'll add links to guide for installing Node.js, because it might not be clear that you need it.
Also, I added `npm install` in setup, because I simply forgot about it. It should install every needed dependency without need for manual install.

**Comment by Bjornskjald** [comment]
@ShinNinth alright, I found the culprit. I'm gonna make the hotfix for it today or tomorrow.

**Comment by Bjornskjald** [comment]
Sorry, didn't see your question. Yes, it works for group chats too.

**Comment by ShinNinth** [comment]
@Bjornskjald Very nice the new readme is pretty straightforward and the node and npm instructions helped clear those parts up greatly.  I have a other things but ill open another issue instead of hijacking this one again. Good work!
