### ISSUE TITLE
Thumbs up icon on facebook does not transfer over

### ISSUE THREAD

**Issue by talormanda** [Bjornskjald/messenger-discord#63]
![capture](https://user-images.githubusercontent.com/10092964/36645716-0874694e-1a3b-11e8-8da2-0a9b39a57854.PNG)

Does not show up correctly.

**Comment by Bjornskjald** [comment]
It could show as a thumbnail, if Facebook wouldn't place some weird extensions in the URL.
I'll see what I can do about it

**Comment by talormanda** [comment]
Just reporting in. Thanks for making this!

**Comment by Bjornskjald** [comment]
I'm currently waiting for Travis check and merging in last fixes, I'm not sure if this works with all of the stickers, but surely with the "thumbs up".

**Comment by Bjornskjald** [comment]
@talormanda Alright, it should work now.

**Comment by talormanda** [comment]
@Bjornskjald do i have to redownload the package and install?

**Comment by Bjornskjald** [comment]
If you downloaded the .zip, you should be able to just replace the `createEmbed.js` file in `lib` folder, but redownloading is the most correct way to upgrade in the case of bigger updates. (existing config.json should work across all 2.x.x versions)

**Comment by talormanda** [comment]
@Bjornskjald Just tested on my raspberry pi, works!

![capture](https://user-images.githubusercontent.com/10092964/36647622-985254d4-1a56-11e8-9935-694a46244888.PNG)
