### ISSUE TITLE
Embeds from other bots do not show up on facebook

### ISSUE THREAD

**Issue by talormanda** [Bjornskjald/messenger-discord#67]
If I have a bot posting a message that is an embed that has text and a photo, it does not show anything when going to facebook.

![pkmn](https://user-images.githubusercontent.com/10092964/36650198-2c329ff6-1a70-11e8-9730-e80a7c12b022.png)

**Comment by Bjornskjald** [comment]
There is no actual way to show an embed in Messenger other that rendering that embed as an image or just converting all the text from the embed to a single message and attach the image.
I'll test this and see what I can do

**Comment by talormanda** [comment]
@Bjornskjald either would be fine imo.

**Comment by Bjornskjald** [comment]
Rendering as an image would be too slow, so I'll do this by converting to plaintext message. I hope it'll work

**Comment by talormanda** [comment]
Cool thanks!

**Comment by Bjornskjald** [comment]
@talormanda It should be working now, I tested it with 2 different bots. I'm merging it to master in a few minutes

**Comment by Bjornskjald** [comment]
Could you test it on your server? If something doesn't work, show screenshots and I'll try to make this fix better.

**Comment by talormanda** [comment]
@Bjornskjald It works, I see all the text. One question: If some of the text is a link, is there any way to extract that?

**Comment by Bjornskjald** [comment]
I think there should be a way, but if it's in text (Markdown) then it would mean implementing whole Markdown parser just for one link...
Also, Facebook doesn't really have a nice way to show links in the message other than just placing it in as text

**Comment by talormanda** [comment]
@Bjornskjald I wouldnt care if the link was extracted and simply at the end of the message. appreciate everything so far! i will test anything you got in the future.

**Comment by Bjornskjald** [comment]
Moved this issue to #69.
