### ISSUE TITLE
Duplicate messages

### ISSUE THREAD

**Issue by talormanda** [Bjornskjald/messenger-discord#71]
Does not happen every time, but there will be duplicate messages sent on discord when there only exists 1 of on facebook.

**Comment by Bjornskjald** [comment]
It's because new messages from the same person are edited into the last message, but it doesn't send the notification, so there is another message sent just to trigger notification and immediately deleted.
In this case it seems as the messages are not deleted fast enough to not show on Discord...

**Comment by Bjornskjald** [comment]
https://github.com/Bjornskjald/messenger-discord/blob/e82013f75a3580f4a3d9231565792a99a62cada0/index.js#L85

**Comment by Bjornskjald** [comment]
Sorry, I couldn't find a better way to show a notification without that temporary message... I think I'll just add a switch for this in config or something
